/* Local named-collection receiving. Reconstructed recovery driver, new identity.
 * node tools/check_named_collection_browser.cjs SOURCE OUTPUT
 * Native producer is current run_agent with explicit FixtureTransport/ScriptedModel;
 * no hosted backend, provider, Actions or deployment is claimed.
 */
const A=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http'),C=require('node:crypto'),{spawnSync}=require('node:child_process');
const {chromium}=require(path.join(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES,'playwright'));
const src=path.resolve(process.argv[2]),out=path.resolve(process.argv[3]);fs.mkdirSync(out);
const sha=b=>C.createHash('sha256').update(b).digest('hex');
const manifest=()=>Object.fromEntries(fs.readdirSync(path.join(src,'static')).sort().map(n=>['static/'+n,sha(fs.readFileSync(path.join(src,'static',n)))]));
const report={schema:'named-collection-recovery-browser/1',parent:process.env.TASTETABLE_REVIEW_PARENT||null,qualificationBaseline:'328df51af830e91f304417a66d74f43d94ae0c02',startedAt:new Date().toISOString(),node:process.version,driverSha256:sha(fs.readFileSync(__filename)),sourceBefore:manifest(),cases:[],requests:[],external:[],errors:[],served:{}};
const run=spawnSync(process.env.CODEX_PRIMARY_RUNTIME_PYTHON||'python3',['-B','-c','import sys,json;sys.path.insert(0,sys.argv[1]);from personas import PERSONAS;from agent import run_agent,ScriptedModel;from qloo_client import QlooClient,FixtureTransport;print(json.dumps({"personas":list(PERSONAS.values()),"responses":{k:run_agent(v,qloo=QlooClient(api_key="MOCK-NOT-A-KEY",transport=FixtureTransport()),model=ScriptedModel()) for k,v in PERSONAS.items()}},ensure_ascii=False))',src],{encoding:'utf8',timeout:20000});
A.equal(run.status,0,run.stderr);const native=JSON.parse(run.stdout);fs.writeFileSync(path.join(out,'native-responses.json'),run.stdout);report.nativeSha256=sha(run.stdout);
let forced=null,browser,base,contexts=[],n=0;
const server=http.createServer(async(q,r)=>{for await(const c of q){}const u=new URL(q.url,'http://localhost');report.requests.push({method:q.method,path:u.pathname});const json=x=>{r.writeHead(200,{'Content-Type':'application/json'});r.end(JSON.stringify(x));};
if(u.pathname==='/api/health')return json({qloo_mode:'mock'});if(u.pathname==='/api/personas')return json(native.personas);
if(u.pathname.startsWith('/api/plan')){const v=forced||native.responses[u.pathname.split('/').at(-1)]||native.responses.rosa;forced=null;return json(v);}
if(u.pathname==='/empty'){r.writeHead(200,{'Content-Type':'text/html'});return r.end('<!doctype html><title>Owned setup</title>');}
const rel=u.pathname==='/'?'static/index.html':u.pathname.slice(1),f=path.resolve(src,rel);if(!rel.startsWith('static/')||!f.startsWith(path.join(src,'static')+path.sep)||!fs.existsSync(f)){r.writeHead(404);return r.end();}const b=fs.readFileSync(f);report.served[rel]=sha(b);r.writeHead(200,{'Content-Type':f.endsWith('.html')?'text/html':f.endsWith('.css')?'text/css':'text/javascript','Cache-Control':'no-store'});r.end(b);});
async function fresh(init=null,empty=false){const context=await browser.newContext({acceptDownloads:true,serviceWorkers:'block',viewport:{width:1280,height:960}});contexts.push(context);await context.route('**/*',rt=>{if(rt.request().url().startsWith(base+'/'))return rt.continue();report.external.push(rt.request().url());return rt.abort();});if(init)await context.addInitScript(init);context.on('page',p=>p.on('pageerror',e=>report.errors.push(e.message)));const page=await context.newPage();page.setDefaultTimeout(12000);await page.goto(base+(empty?'/empty':'/'));if(!empty)await ready(page);return{context,page};}
const ready=p=>p.waitForFunction(()=>document.querySelector('#personaSel').options.length===3);
async function sample(p,id='rosa'){await p.selectOption('#personaSel',id);await p.click('#sampleBtn');await p.waitForFunction(()=>!document.querySelector('#results').hidden&&document.querySelector('#weekDays select'));}
async function store(p,method,args=[]){return p.evaluate(async({method,args})=>{const{createSavedWeekStore}=await import('/static/saved_week_store.mjs');const s=createSavedWeekStore();try{return await s[method](...args);}finally{s.close();}},{method,args});}
async function save(p,name,count){await p.fill('#savedWeekName',name);await p.click('#saveCurrentWeek');await p.waitForFunction(n=>document.querySelector('#savedWeeksStatus').textContent.startsWith('Saved “')&&document.querySelectorAll('#savedWeeksList>li').length===n,count);return(await store(p,'list')).find(r=>r.draft?.name===name).draft;}
async function preview(p,id){await p.click('#refreshSavedWeeks');await p.locator('button[data-saved-week-id="'+id+'"]').click();await p.waitForFunction(()=>!document.querySelector('#savedWeekPreview').hidden&&!document.querySelector('#openSavedWeek').disabled);}
async function open(p){await p.click('#openSavedWeek');await p.waitForFunction(()=>document.querySelector('#requestStatus').textContent.startsWith('Saved week opened.'));}
async function file(p,selector,name){const wait=p.waitForEvent('download');await p.click(selector);const d=await wait;const f=path.join(out,String(++n)+'-'+name);await d.saveAs(f);return fs.readFileSync(f,'utf8');}
function identity(t){const j=JSON.parse(t);delete j.savedAt;return j;}
async function state(p){return p.evaluate(()=>({date:document.querySelector('#weekDate').value,assignments:Object.fromEntries([...document.querySelectorAll('[data-pick-key]')].map(x=>[x.dataset.pickKey,x.value||null])),source:document.querySelector('#weekSource').textContent,original:document.querySelector('.original-evidence').textContent}));}
async function raw(p,values){await p.evaluate(values=>new Promise((yes,no)=>{const q=indexedDB.open('tastetable.saved-weeks',1);q.onerror=()=>no(q.error.message);q.onsuccess=()=>{const db=q.result,tx=db.transaction('drafts','readwrite');values.forEach(v=>tx.objectStore('drafts').put(v));tx.oncomplete=()=>{db.close();yes();};tx.onabort=()=>{db.close();no(tx.error?.message);};};}),values);}
async function lock(p){await p.evaluate(()=>new Promise((yes,no)=>{const q=indexedDB.open('tastetable.saved-weeks',1);q.onerror=()=>no(q.error.message);q.onsuccess=()=>{const db=q.result,tx=db.transaction('drafts','readwrite'),s=tx.objectStore('drafts');let done=false;window.releaseCollectionLock=()=>done=true;function keep(){s.get('__hold__').onsuccess=()=>{if(!done)keep();};}keep();tx.oncomplete=()=>db.close();yes();};}));}
async function check(name,fn){const start=contexts.length;try{const detail=await fn();report.cases.push({name,passed:true,detail});console.log('PASS '+name);}catch(e){report.cases.push({name,passed:false,error:e.stack});throw e;}finally{for(const c of contexts.slice(start))await c.close();}}
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));base='http://127.0.0.1:'+server.address().port;browser=await chromium.launch({executablePath:process.env.TASTETABLE_REVIEW_CHROMIUM||'/workspace/scratch/a4a1879c582f/t95-receiving/browser/chromium',headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--disable-background-networking']});report.browser=browser.version();
await check('Save reload Preview Open preserves canonical identity and admits matching current venue-note companion',async()=>{const{page:p}=await fresh();await sample(p);await p.fill('#weekDate','2026-12-31');await p.selectOption('[data-pick-key="pick-0"]','Wednesday');await p.selectOption('[data-pick-key="pick-1"]','');await p.locator('[data-contact-field="reply"]').first().fill('Sentinel call note');const expected=await state(p),ics=await file(p,'#calendarDownload','before.ics'),notes=await file(p,'[data-contact-file-save]','notes.json');const d=await save(p,'Café family — winter',1),parsed=JSON.parse(d.text);expected.date=parsed.week.start;A.equal(expected.date,'2026-12-28');A.deepEqual(parsed.response,native.responses.rosa);A.equal(d.text.includes('Sentinel call note'),false);A.deepEqual(identity(await file(p,'#saveWeek','before.json')),identity(d.text));await p.reload();await ready(p);await preview(p,d.id);A.equal(await p.locator('#results').isHidden(),true);const posts=report.requests.filter(x=>x.method==='POST').length;await open(p);A.deepEqual(await state(p),expected);A.equal(report.requests.filter(x=>x.method==='POST').length,posts);A.equal(await p.locator('[data-contact-field="reply"]').first().inputValue(),'');await p.locator('[data-contact-file-input]').setInputFiles({name:'matching-notes.json',mimeType:'application/json',buffer:Buffer.from(notes)});await p.locator('[data-contact-file-preview]').waitFor({state:'visible'});await p.click('[data-contact-file-apply]');await p.waitForFunction(()=>document.querySelector('[data-contact-field="reply"]').value==='Sentinel call note');A.equal(await file(p,'#calendarDownload','reopened.ics'),ics);A.deepEqual(identity(await file(p,'#saveWeek','reopened.json')),identity(d.text));A.equal(await p.locator('#saveCurrentWeek').isEnabled(),true);await p.emulateMedia({media:'print'});A.equal(await p.locator('#savedWeeks').evaluate(e=>getComputedStyle(e).display),'none');await p.emulateMedia({media:'screen'});await p.locator('#savedWeeks').screenshot({path:path.join(out,'desktop.jpg'),type:'jpeg',quality:65});await p.setViewportSize({width:390,height:844});A.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await p.locator('#savedWeeks').screenshot({path:path.join(out,'phone.jpg'),type:'jpeg',quality:65});return{calendarSha256:sha(ics),canonicalSha256:sha(d.text),receivedAt:parsed.receivedAt,calendarId:parsed.calendarId,worksheetCompanionAccepted:true};});
await check('Dirty Rename survives delayed native focus refresh and explicit other Preview initializes its own name',async()=>{const{page:p}=await fresh();await sample(p);const a=await save(p,'Original',1);await preview(p,a.id);await lock(p);await p.evaluate(()=>window.dispatchEvent(new Event('focus')));await p.fill('#renameSavedWeekName','Typed during refresh');await p.evaluate(()=>window.releaseCollectionLock());await store(p,'list');A.equal(await p.locator('#renameSavedWeekName').inputValue(),'Typed during refresh');await p.click('#renameSavedWeek');await p.waitForFunction(()=>document.querySelector('#savedWeeksStatus').textContent.startsWith('Renamed'));const x=await store(p,'get',[a.id]);A.equal(x.name,'Typed during refresh');A.equal(x.text,a.text);const b=await save(p,'Other',2);await preview(p,a.id);await p.fill('#renameSavedWeekName','Discard on selection');await preview(p,b.id);A.equal(await p.locator('#renameSavedWeekName').inputValue(),'Other');return{nativeReadDelayed:true,dirtyInputPreserved:true,newSelectionInitialized:true};});
await check('Two-tab independent saves and selected rename/remove preserve canonical text and current plan',async()=>{const{context,page:a}=await fresh();await sample(a);const original=await save(a,'Original',1);const b=await context.newPage();await b.goto(base);await ready(b);await sample(b,'mei');await a.fill('#savedWeekName','Tab A');await b.fill('#savedWeekName','Tab B');await Promise.all([a.click('#saveCurrentWeek'),b.click('#saveCurrentWeek')]);await Promise.all([a.waitForFunction(()=>document.querySelector('#savedWeeksStatus').textContent.startsWith('Saved “')),b.waitForFunction(()=>document.querySelector('#savedWeeksStatus').textContent.startsWith('Saved “'))]);const all=await store(a,'list');A.equal(all.length,3);await preview(a,original.id);const before=await state(a);await a.fill('#renameSavedWeekName','Literal <care> & family');await a.click('#renameSavedWeek');await a.waitForFunction(()=>document.querySelector('#savedWeeksStatus').textContent.startsWith('Renamed'));const renamed=await store(b,'get',[original.id]);A.equal(renamed.name,'Literal <care> & family');A.equal(renamed.text,original.text);A.equal(await a.locator('#savedPreviewTitle care').count(),0);await store(b,'remove',[all.find(r=>r.draft.name==='Tab B').id]);A.equal((await store(a,'list')).length,2);A.deepEqual(await state(a),before);return{copiesBeforeRemove:3,afterRemove:2,canonicalTextUnchanged:true};});
await check('Native transaction abort after successful add is not reported as a Save',async()=>{const{page:p}=await fresh();await sample(p);const old=await save(p,'Keep',1);await p.evaluate(()=>{const add=IDBObjectStore.prototype.add;window.restoreAdd=()=>IDBObjectStore.prototype.add=add;IDBObjectStore.prototype.add=function(...a){const r=add.apply(this,a),t=this.transaction;r.addEventListener('success',()=>t.abort(),{once:true});return r;};});await p.fill('#savedWeekName','Abort');await p.click('#saveCurrentWeek');await p.waitForFunction(()=>document.querySelector('#savedWeeksStatus').textContent.includes('storage is unavailable'));await p.evaluate(()=>window.restoreAdd());const all=await store(p,'list');A.equal(all.length,1);A.equal(all[0].draft.text,old.text);A.equal(await p.locator('#saveWeek').isEnabled(),true);return{abortedRecordAbsent:true,oldCopyUnchanged:true};});
await check('Corrupt and future local records remain refused and explicitly removable',async()=>{const{page:p}=await fresh();await sample(p);const d=await save(p,'Valid',1);await raw(p,[{...d,id:'corrupt_0001',text:'{'},{...d,id:'future_00001',version:99}]);await p.click('#refreshSavedWeeks');await p.waitForFunction(()=>document.querySelectorAll('#savedWeeksList>li').length===3);await p.locator('button[data-saved-week-id="corrupt_0001"]').click();A.equal(await p.locator('#openSavedWeek').isDisabled(),true);await p.click('#removeSavedWeek');await p.waitForFunction(()=>document.querySelectorAll('#savedWeeksList>li').length===2);A.equal((await store(p,'get',[d.id])).text,d.text);A.ok((await store(p,'list')).find(r=>r.id==='future_00001').error);return{futureRecordRetained:true,validCopyUnchanged:true};});
await check('Concurrent native transactions enforce the fifty-copy bound',async()=>{const{context,page:a}=await fresh();await sample(a);const d=await save(a,'Seed',1);await raw(a,Array.from({length:48},(_,i)=>({...d,id:'capacity_'+String(i).padStart(4,'0'),name:'Seed '+i})));const b=await context.newPage();await b.goto(base);await ready(b);await sample(b,'mei');await a.fill('#savedWeekName','Race A');await b.fill('#savedWeekName','Race B');await Promise.all([a.click('#saveCurrentWeek'),b.click('#saveCurrentWeek')]);await Promise.all([a.waitForFunction(()=>!document.querySelector('#saveCurrentWeek').disabled),b.waitForFunction(()=>!document.querySelector('#saveCurrentWeek').disabled)]);const all=await store(a,'list');A.equal(all.length,50);A.equal(all.filter(r=>['Race A','Race B'].includes(r.draft?.name)).length,1);const statuses=await Promise.all([a.locator('#savedWeeksStatus').textContent(),b.locator('#savedWeeksStatus').textContent()]);A.equal(statuses.filter(s=>s.includes('already has 50')).length,1);return{records:50,concurrentSuccesses:1};});
await check('Late valid collection Open retires immediately and cannot replace newer accepted provider identity',async()=>{const{page:p}=await fresh();await sample(p);const d=await save(p,'Old',1);await preview(p,d.id);await lock(p);await p.click('#openSavedWeek');A.equal(await p.locator('#results').isHidden(),true);A.equal(await p.locator('#venueFollowup').isHidden(),true);await sample(p,'mei');const newer=await file(p,'#saveWeek','newer.json'),ics=await file(p,'#calendarDownload','newer.ics');await p.evaluate(()=>window.releaseCollectionLock());await p.waitForFunction(()=>document.querySelector('#savedWeeksStatus').textContent.includes('not opened'));A.equal(await p.locator('#savedWeekSource').isHidden(),true);A.deepEqual(identity(await file(p,'#saveWeek','after-late.json')),identity(newer));A.equal(await file(p,'#calendarDownload','after-late.ics'),ics);return{immediateRetirement:true,newerAcceptedIdentityPreserved:true};});
await check('Invalid displayed date disables Save and unknown all-omitted copies retain truthful source',async()=>{const{page:p}=await fresh();forced=structuredClone(native.responses.rosa);delete forced.mock;await sample(p);const keys=await p.locator('[data-pick-key]').evaluateAll(es=>es.map(e=>e.dataset.pickKey));for(const k of keys)await p.selectOption('[data-pick-key="'+k+'"]','');await p.fill('#weekDate','');A.equal(await p.locator('#saveCurrentWeek').isDisabled(),true);await p.fill('#weekDate','2027-01-06');const d=await save(p,'Omitted unknown',1);await preview(p,d.id);A.match(await p.locator('#savedPreviewSource').textContent(),/unspecified/);await open(p);A.equal(await p.locator('#weekDays .scheduled-pick').count(),0);A.equal(await p.locator('#omittedPicks .scheduled-pick').count(),keys.length);A.equal(await p.locator('#calendarDownload').isDisabled(),true);return{omitted:keys.length,calendarDisabled:true};});
await check('Blocked storage and future database version preserve data and portable Save availability',async()=>{const{page:b}=await fresh(()=>Object.defineProperty(window,'indexedDB',{get(){throw new DOMException('Blocked','SecurityError');}}));await sample(b);await b.waitForFunction(()=>document.querySelector('#savedWeeksStatus').textContent.includes('preventing'));A.equal(await b.locator('#saveCurrentWeek').isDisabled(),true);A.equal(await b.locator('#saveWeek').isEnabled(),true);const{page:p}=await fresh(null,true);await p.evaluate(()=>new Promise((r,j)=>{const q=indexedDB.open('tastetable.saved-weeks',2);q.onupgradeneeded=()=>q.result.createObjectStore('future',{keyPath:'id'}).put({id:'kept',value:'retained'});q.onerror=()=>j(q.error.message);q.onsuccess=()=>{q.result.close();r();};}));await p.goto(base);await ready(p);await sample(p);await p.waitForFunction(()=>document.querySelector('#savedWeeksStatus').textContent.includes('newer app version'));const kept=await p.evaluate(()=>new Promise(r=>{const q=indexedDB.open('tastetable.saved-weeks',2);q.onsuccess=()=>{const db=q.result,g=db.transaction('future').objectStore('future').get('kept');g.onsuccess=()=>{db.close();r(g.result);};};}));A.deepEqual(kept,{id:'kept',value:'retained'});A.equal(await p.locator('#savedWeeksEmpty').isHidden(),true);A.equal(await p.locator('#saveWeek').isEnabled(),true);return{futureDataRetained:true,portableSaveAvailable:true};});
A.deepEqual(report.errors,[]);A.deepEqual(report.external,[]);report.passed=true;
})().catch(e=>{report.passed=false;report.error=e.stack;console.error(e.stack);process.exitCode=1;}).finally(async()=>{for(const c of contexts)await c.close().catch(()=>{});await browser?.close();server.closeAllConnections();await new Promise(r=>server.close(r));report.sourceAfter=manifest();report.sourceUnchanged=JSON.stringify(report.sourceBefore)===JSON.stringify(report.sourceAfter);if(!report.sourceUnchanged){report.passed=false;process.exitCode=1;}report.finishedAt=new Date().toISOString();report.artifacts=fs.readdirSync(out).map(name=>({name,bytes:fs.statSync(path.join(out,name)).size,sha256:sha(fs.readFileSync(path.join(out,name)))}));fs.writeFileSync(path.join(out,'receiving-report.json'),JSON.stringify(report,null,2)+'\n');console.log('NAMED_RECOVERY_RESULT '+JSON.stringify({passed:report.passed,cases:report.cases.length,sourceUnchanged:report.sourceUnchanged}));});
